/*
 * Builds an inline SVG sprite from the vendored Lucide bundle.
 *
 * Shipping lucide.min.js would cost 347KB and a DOM sweep on every page to
 * render about twenty icons. This extracts just the ones the app uses into a
 * ~6KB sprite that is inlined into the base template, so there is no icon
 * library at runtime at all.
 *
 *   node scripts/build_icon_sprite.js
 */

const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const BUNDLE = path.join(__dirname, "vendor/lucide.min.js");
const OUT = path.join(ROOT, "src/modelops/web/templates/_icons.html");

// Sprite id -> Lucide export name.
const WANTED = {
  // Navigation
  "nav-operations": "Gauge",
  "nav-jobs": "ListChecks",
  "nav-catalog": "Database",
  "nav-packages": "Package",
  "nav-handover": "ArrowRightLeft",
  "nav-viewer": "Box",
  "nav-sql": "Terminal",
  "nav-docs": "BookOpen",
  // Brand
  "brand": "Layers",
  // Controls and states
  "ask": "Sparkles",
  "close": "X",
  "send": "ArrowUp",
  "download": "Download",
  "play": "Play",
  "pause": "Pause",
  "external": "ExternalLink",
  "alert": "TriangleAlert",
  "ok": "CircleCheck",
  "blocked": "CircleAlert",
  "clock": "Clock",
  "search": "Search",
  "isolate": "Crosshair",
  "chevron": "ChevronRight",
};

const mod = { exports: {} };
new Function("module", "exports", fs.readFileSync(BUNDLE, "utf8"))(mod, mod.exports);
const lucide = mod.exports;

function attrs(obj) {
  return Object.entries(obj)
    .map(([k, v]) => ` ${k}="${v}"`)
    .join("");
}

const symbols = [];
const missing = [];

for (const [id, name] of Object.entries(WANTED)) {
  const icon = lucide[name];
  if (!icon) {
    missing.push(`${id} (${name})`);
    continue;
  }
  const children = icon[2]
    .map(([tag, a]) => `<${tag}${attrs(a)}/>`)
    .join("");
  // Stroke attributes have to live on the symbol, not on the sprite root:
  // <use> content inherits from the <use> element's position in the document,
  // not from where the symbol was defined.
  symbols.push(
    `<symbol id="i-${id}" viewBox="0 0 24 24" fill="none" stroke="currentColor"` +
    ` stroke-width="2" stroke-linecap="round" stroke-linejoin="round">` +
    `${children}</symbol>`
  );
}

if (missing.length) {
  console.error("Not found in the Lucide bundle: " + missing.join(", "));
  process.exit(1);
}

const version =
  (fs.readFileSync(BUNDLE, "utf8").match(/lucide v([\d.]+)/) || [, "?"])[1];

const out = `{# Generated by scripts/build_icon_sprite.js - do not edit by hand. #}
{# Lucide v${version}, ISC licence. Only the icons the app actually uses. #}
<svg xmlns="http://www.w3.org/2000/svg" width="0" height="0"
     style="position:absolute" aria-hidden="true" focusable="false">
${symbols.join("\n")}
</svg>
`;

fs.writeFileSync(OUT, out, "utf8");
console.log(
  `Wrote ${symbols.length} icons to ${path.relative(ROOT, OUT)} ` +
  `(${(Buffer.byteLength(out) / 1024).toFixed(1)}KB)`
);
